### PR TITLE
Fix #2 Do not require local figwheel-bridge.js

### LINKED ISSUE #2: Do not require local figwheel-bridge.js
In order to hook RN with figwheel `re-natal` introduces a local `figwheel-bridge.js` file.

 Make sure that this file is not required locally. It should still be possible to make local adaptation, if relevant.

It might be worth looking into how clojurescript [handles](https://github.com/clojure/clojurescript/blob/27c27e0b53f6ef550670d7aed981395a96aae1da/src/main/clojure/cljs/closure.clj#L1674) different targets (nodejs, webworker).

### PR DESCRIPTION
**Pull request by psdp**
It now has a local copy of `figwheel-bridge.js` in `resources` dir that would be copied to `target/` dir of RN project every time when recreating `index.*.js`, then being loaded from `index.*.js`. You can specify your own `figwheel-bridge.js` by setting a value for `:figwheel-bridge` var in `clj-rn.conf.edn`.

### CODE REVIEW

**Comment by jeluard** [comment]
Thanks for the PR!

I was secretly hoping we could remove part of the bridge altogether. Could you comment on why this is needed and what it does by any chance?

**Comment by psdp** [comment]
@jeluard Sorry, I don't really get the idea of how you want to remove `figwheel-bridge.js`. bundle it in `index.js`?
I think we certainly need some features provided in `figwheel-bridge.js` for starting an app.

**Comment by jeluard** [comment]
It's probably me not figuring out details.
Could you detail at high level what it does?

**Comment by psdp** [comment]
@jeluard So the main goal of the PR is to move `figwheel-bridge.js` away from a RN project codebase and keep one copy in `CLJ-RN` lib and load from there instead. It is still being loaded by `index.js` however. Not really sure how it can be removed completely.

**Comment by jeluard** [comment]
Right!
Actually I was wondering what the bridge file does.

**Comment by psdp** [comment]
@jeluard from my observation what `figwheel-bridge.js` does:

1. Create a dummy react native view to initialize the app
2. Load Closure lib along with other required libs into the app
3. Connect to the main app and listen to figwheel messages
4. Render the main app and display figwheel messages on the screen if any

**Comment by flexsurfer** [comment]
https://github.com/drapanjanas/re-natal/pull/185 would be good to include this change

**Comment by jeluard** [comment]
@flexsurfer @psdp Right we definitively want that!

**Comment by jeluard** [comment]
@psdp So 1. and 2. are figwheel agnostic? Probably something we could hook directly in the ClojureScript compiler. Will consider this for another issue.

**Comment by psdp** [comment]
Updated `figwheel-bridge.js` to the latest from `re-natal`. I've tested that it is working. Just a few things to note, we need to do the following changes in an existing RN project:

- Upgrade `reagent` version to "0.8.1"
- Downgrade `figwheel-sidecar` to "0.5.14"
- Add `:target :nodejs` and remove `:npm-deps false` from CLJS build compiler options

Either figwheel connection could not be established or CLJS compiler throwing errors when not doing so.

**Comment by jeluard** [comment]
Awesome! @psdp Could you finally add some section in the readme detailing those constraints?

**Comment by psdp** [comment]
Updated README. Let me know if there is anything unclear.

P.S. I checked again and found that upgrading reagent to version `0.8.1` is not necessary, not sure if things will break for a big project like `status-react`.

**Comment by jeluard** [comment]
@psdp Looks good! @flexsurfer WDYT?

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by jeluard** [comment]
@psdp Thanks for your contribution!

**Pull request merged**
